### ISSUE TITLE
Redis 캐싱 적용

### ISSUE THREAD

**Issue by DevBloo** [Team-Delight/Delight-Server#27]
자주 호출 되는 API에 캐싱을 적용한다.

### Task

- [x] - Redis 적용
- [x] - 캐싱을 하는 이유 정리
- [ ] - ranking data 에 캐싱 추가
- [x] - 음식 목로 조회에 캐싱 추가
